server:
  port:  8080
#  servlet:
#    context-path: /oauth2-gateway
#    session:
#      cookie:
#        name: GATEWAY_SESSION
#        path: /oauth2-gateway

  ssl:
    name:                 my-oauth2
    key-store-provider:   SUN
    key-store-type:       JKS
    key-store:            classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password:   forsrc
    key-alias:            ${server.ssl.name}.server
    enabled:              true
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need

#oauth-server:  https://my-oauth2:20000
#rource-server: https://my-oauth2:21000

#oauth2-server:        https://my-oauth2-server:20000/oauth2-server
oauth2-server:        http://my-oauth2:20000/oauth2-server
oauth2-rource-server: http://my-oauth2:21000/oauth2-resource-server
oauth2-client:        http://my-oauth2:22000/oauth2-client


spring:
  cloud:
    gateway:
      routes:
      - id:          oauth2_server
        uri:         http://my-oauth2:20000/oauth2-server
        predicates:
        -            Path=/oauth2-server/**
        filters:
        - AddRequestHeader=gateway_oauth2_server, https://my-oauth2:8080/oauth2-server/
      - id:          oauth2_client
        uri:         http://my-oauth2:22000/oauth2-client
        predicates:
        -            Path=/oauth2-client/**
        filters:
        - AddRequestHeader=gateway_oauth2_server, https://my-oauth2:8080/oauth2-server/
