my:
  hostname: ${MY_HOST_NAME:oauth2-gateway}
  application-name: oauth2-gateway
  context-path: /${my.application-name}
  session-name: GATEWAY_SESSION
  username: ${MY_USERNAME:forsrc}
  password: ${MY_PASSWORD:forsrc}
  port: ${MY_PORT:443}
#  oauth2-server: http://oauth2-server:20000/oauth2-server
#  oauth2-resource-server: http://oauth2-resource-server:21000/oauth2-resource-server
#  oauth2-client: http://oauth2-client:22000/oauth2-client
  gateway-base-url: ${MY_GATEWAY:https://oauth2-gateway}
  gateway-oauth2-server: ${my.gateway-base-url}/oauth2-server/
  gateway-oauth2-resource_server: ${my.gateway-base-url}/oauth2-resource-server/
  gateway-oauth2-client: ${my.gateway-base-url}/oauth2-client/
  gateway-oauth2-eureka-server: ${my.gateway-base-url}/oauth2-eureka-server/
  gateway-oauth2-admin-server: ${my.gateway-base-url}/oauth2-admin-server/
  eureka-server: ${MY_EUREKA_SERVER:oauth2-eureka-server:23000}
  admin-server: ${MY_ADMIN_SERVER:oauth2-admin-server:24000}