server:
  port:  22000
  servlet:
    context-path: /oauth2-client
    session:
      cookie:
        name: CLIENT_SESSION

  ssl:
    name:                 my-oauth2
    key-store-provider:   SUN
    key-store-type:       JKS
    key-store:            classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password:   forsrc
    key-alias:            ${server.ssl.name}.server
    enabled:              false
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need

#oauth-server:  https://my-oauth2:20000
#rource-server: https://my-oauth2:21000

oauth2-server:        http://my-oauth2:20000/oauth2-server
oauth2-rource-server: http://my-oauth2:21000/oauth2-resource-server
oauth2-client:        http://my-oauth2:22000/oauth2-client

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id:                    ui
      client-secret:                forsrc
      access-token-uri:             ${oauth2-server}/oauth/token
      user-authorization-uri:       ${oauth2-server}/oauth/authorize
      scope:                        ui, read, write
    resource:
      token-info-uri:               ${oauth2-server}/oauth/check_token
      user-info-uri:                ${oauth2-server}/user/me
#      jwt:
#        key-uri:      ${oauth2-server}/oauth/token_key


spring:
  application:    name:      oauth2-client
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

eureka:
  instance:
    prefer-ip-address: true
    hostname:          my-oauth2
    instance-id:       ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    appname:           ${spring.application.name}
  client:
    service-url:
      defaultZone: http://forsrc:forsrc@my-oauth2:23000/oauth2-eureka-server/eureka

management:
  endpoints:
    web:
      exposure:
        include:    "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.security: INFO