server:
  port:  22000
  servlet:
    session:
      cookie:
        name: CLIENT_SESSION

  ssl:
    name:                 my-oauth2
    key-store-provider:   SUN
    key-store-type:       JKS
    key-store:            classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password:   forsrc
    key-alias:            ${server.ssl.name}.server
    enabled:              true
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need

#oauth-server:  https://my-oauth2:20000
#rource-server: https://my-oauth2:21000

oauth-server:  https://my-oauth2:20000
rource-server: https://my-oauth2:21000
oauth-client:  https://my-oauth2:22000

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id:                    forsrc
      client-secret:                forsrc
      access-token-uri:             ${oauth-server}/oauth/token
      user-authorization-uri:       ${oauth-server}/oauth/authorize
      scope:                        ui, read, write
#      pre-established-redirect-uri: ${oauth-client}/login
#      use-current-uri:              false
    resource:
      token-info-uri:               ${oauth-server}/oauth/check_token
      user-info-uri:                ${oauth-server}/user/me
#      prefer-token-info:            false

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.springframework.security: INFO