my:
  hostname: ${MY_HOST_NAME:oauth2-admin-server}
  application-name: oauth2-admin-server
  session-name: ADMIN_SESSION
  port: 8080
  eureka-server: ${MY_EUREKA_SERVER:http://forsrc:forsrc@oauth2-eureka-server:8080/eureka}