server:
  port:  24000
  servlet:
    context-path: /oauth2-admin-server
    session:
      cookie:
        name: EUREKA_SESSION
        path: /oauth2-admin-server

  ssl:
    name:                 my-oauth2
    key-store-provider:   SUN
    key-store-type:       JKS
    key-store:            classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password:   forsrc
    key-alias:            ${server.ssl.name}.server
    enabled:              false
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need

spring:
  freemarker.prefer-file-system-access: false
  application:
    name:       oauth2-admin-server
  boot:
    admin:
      client:
        url:                http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}
        username:           forsrc
        password:           forsrc
        instance:          management-base-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}
#  security:
#    basic:
#      enabled:  true
#    user:
#      name:     forsrc
#      password: forsrc
  security:
    basic:      enabled:  true    user:      name:     forsrc
      password: forsrc


eureka:
  instance:
    prefer-ip-address:              true
    hostname:                       my-oauth2
    instance-id:                    ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    appname:                        ${spring.application.name}
    leaseRenewalIntervalInSeconds:  10
    health-check-url-path:          /actuator/health
    metadata-map:
      management.context-path:      ${server.servlet.context-path}/actuator
      user.name:                    forsrc
      user.password:                forsrc
  client:
    service-url:
      defaultZone:                  http://forsrc:forsrc@my-oauth2:23000/oauth2-eureka-server/eureka

management:
  endpoints:
    web:
      exposure:
        include:    "*"
  endpoint:
    health:
      show-details: ALWAYS