server:
  port:  21000
  servlet:
    session:
      cookie:
        name: RESOURCE_SERVER_SESSION

  

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:20000/oauth/check_token
      user-info-uri:  http://localhost:20000/user/me
    client:
      client-id:      forsrc
      client-secret:  forsrc

