server:
  port:  21000
  servlet:
    context-path: /oauth2-resource-server
    session:
      cookie:
        name: RESOURCE_SERVER_SESSION

  ssl:
    name:                 my-oauth2
    key-store-provider:   SUN
    key-store-type:       JKS
    key-store:            classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password:   forsrc
    key-alias:            ${server.ssl.name}.server
    enabled:              false
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need 

oauth2-server:        http://my-oauth2:20000/oauth2-server
#oauth2-server:        https://my-oauth2:8080/oauth2-server

#oauth2-rource-server: https://my-oauth2:21000/oauth2-resource-server
#oauth2-client:        https://my-oauth2:22000/oauth2-client

security:
  oauth2:
    client:
      client-id:      ui
      client-secret:  forsrc
      scope:          ui, read, write
    resource:
      #token-info-uri: ${oauth2-server}/oauth/check_token
      user-info-uri:  ${oauth2-server}/user/me
      #preferTokenInfo: true
#      jwt:
#        key-uri:      ${oauth2-server}/oauth/token_key


#security:
#  oauth2:
#    resource:
#      jwk:
#        key-set-uri:   ${oauth2-server}/oauth/jwks


logging:
  level:
    org.springframework.security: debug
