my:
  hostname: ${MY_HOST_NAME:my-oauth2}
  application-name: oauth2-resource-server
  context-path: /${my.application-name}
  session-name: RESOURCE_SERVER_SESSION
  port: 21000
  oauth2-server: http://my-oauth2:20000/oauth2-server
  admin-server: http://my-oauth2:24000/oauth2-admin-server
  eureka-server: http://forsrc:forsrc@my-oauth2:23000/oauth2-eureka-server/eureka

server:
  port: ${my.port}
  servlet:
    context-path: ${my.context-path}
    session:
      cookie:
        name: ${my.session-name}

  ssl:
    name: my-oauth2
    key-store-provider: SUN
    key-store-type: JKS
    key-store: classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password: forsrc
    key-alias: ${server.ssl.name}.server
    enabled: false
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need 



security:
  oauth2:
    client:
      client-id: ui
      client-secret: forsrc
      scope: ui, read, write
    resource:
      #token-info-uri: ${my.oauth2-server}/oauth/check_token
      user-info-uri: ${my.oauth2-server}/user/me
      #preferTokenInfo: true
#      jwt:
#        key-uri:      ${oauth2-server}/oauth/token_key


#security:
#  oauth2:
#    resource:
#      jwk:
#        key-set-uri:   ${oauth2-server}/oauth/jwks
spring:
  application:
    name: oauth2-resource-server
  boot:
    admin:
      client:
        url: ${my.admin-server}
        username: forsrc
        password: forsrc
        instance:
          management-base-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}
eureka:
  instance:
    prefer-ip-address: true
    hostname: my-oauth2
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
      user.name: forsrc
      user.password: forsrc
  client:
    service-url:
      defaultZone: ${my.eureka-server}

management:
  endpoints:

    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.security: info
