my:
  hostname: ${MY_HOST_NAME:oauth2-eureka-server}
  application-name: oauth2-eureka-server
  context-path: /${my.application-name}
  session-name: EUREKA_SESSION
  username: ${MY_USERNAME:forsrc}
  password: ${MY_PASSWORD:forsrc}
  port: 8080
  #  gateway-port: 8080
  #  gateway-port-to-port: 8080
  #  eureka-server: ${MY_EUREKA_SERVER:localhost:8080}
  admin-server: ${MY_ADMIN_SERVER:my-oauth2:8080}