server:
  port:  20000
  servlet:
    context-path: /oauth2-server
    session:
      cookie:
        name: AUTH_SERVER_SESSION
        path: /oauth2-server

  ssl:
    name:                 my-oauth2
    key-store-provider:   SUN
    key-store-type:       JKS
    key-store:            classpath:ssl/${server.ssl.name}.server.keystore
    key-store-password:   forsrc
    key-alias:            ${server.ssl.name}.server
    enabled:              false
    #trust-store-provider: SUN
    #trust-store-type:     JKS
    #trust-store:          classpath:ssl/${server.ssl.name}.server.keystore
    #trust-store-password: forsrc
    #client-auth:          need

oauth2-server:        http://my-oauth2:20000/oauth2-server
oauth2-rource-server: http://my-oauth2:21000/oauth2-resource-server
oauth2-client:        http://my-oauth2:22000/oauth2-client

security:
  user:
    username: forsrc
    password: forsrc
    roles:    USER, ADMIN
  oauth2:
    client:
      client-id:               forsrc
      client-secret:           forsrc
      scope:                   ui, read, write
      auto-approve-scopes:     .*
      authorized-grant-types:  authorization_code, client_credentials, refresh_token, password, implicit
      registered-redirect-uri:
      -                        ${oauth2-client}/login
      -                        ${oauth2-client}/login/oauth2/code/my-oauth2
    authorization:
      check-token-access:      permitAll()
#    resource:#      filter-order:            3

spring:
  main.allow-bean-definition-overriding: true
  application:
    name:      oauth2-server
  datasource:
    url:                 ${DB_URL:jdbc:h2:~/tmp/db/h2/my-oauth2-server.h2;AUTO_SERVER=TRUE;MODE=MYSQL;}
    username:            ${DB_USERNAME:sa}
    password:            ${DB_PASSWORD:sa}
    driver-class-name:   ${DB_DRIVER:org.h2.Driver}
    data:
    - classpath:schema.sql
    - classpath:data.sql
  jpa:
    database-platform:                     ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    show-sql:                              true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show-sql:                  true
      hibernate.hbm2ddl.auto:              update
    open-in-view:                          true
  boot:
    admin:
      client:
        url:                   http://my-oauth2:24000/oauth2-admin-server
        username:              forsrc
        password:              forsrc
        instance:
          management-base-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}

eureka:
  instance:
    prefer-ip-address:              true
    hostname:                       my-oauth2
    instance-id:                    ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    appname:                        ${spring.application.name}
    leaseRenewalIntervalInSeconds:  10
    health-check-url-path:          /actuator/health
    metadata-map:
      management.context-path:      ${server.servlet.context-path}/actuator
      user.name:                    forsrc
      user.password:                forsrc
  client:
    service-url:
      defaultZone:                  http://forsrc:forsrc@my-oauth2:23000/oauth2-eureka-server/eureka

management:
  endpoints:
    web:
      exposure:
        include:    "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.security: info


# openssl pkcs12 -in my-oauth2.server.p12 -out my-oauth2.server.pem -password pass:forsrc -passin pass:forsrc -passout pass:forsrc
# openssl rsa -in my-oauth2.server.pem -outform PEM -pubout -out my-oauth2.server.public.pem -passin pass:forsrc

# openssl genrsa -out private.pem 2048
# openssl rsa -in private.pem -outform PEM -pubout -out public.pem
jwt:
  verifier-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs7bhjRMzACb2lDQqzNpq
    XBBpceTupwCBoYcRD7b1JYjqPUQ04wlPXiEm99Q9GvqS32skcBcYVr0ErHb9X7R5
    oypuDw/k45IU6OvPe9U6HmStgM5i318laOaJL4dlElHNHDzyMT0xavw/ys97roxi
    oMk0BBQKV9+UHd/SzvHq9z9CVcJpqfR0pR15SlvY4Dp/kEzo/bNBw/4hvIY0nFoC
    fP2PTi1G6W05O9o03sEMkvb0Y24SsPiX7Fmr1yqJW+9zBvgfZEuGfp+kS+7ynAkK
    oasy3PFIP7Au445ueEHL0Xtm7u0NjlbavrkQZ5gOQq1P+B3ZFNsEHRrPzCY91lfq
    LwIDAQAB
    -----END PUBLIC KEY-----
  signing-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEAs7bhjRMzACb2lDQqzNpqXBBpceTupwCBoYcRD7b1JYjqPUQ0
    4wlPXiEm99Q9GvqS32skcBcYVr0ErHb9X7R5oypuDw/k45IU6OvPe9U6HmStgM5i
    318laOaJL4dlElHNHDzyMT0xavw/ys97roxioMk0BBQKV9+UHd/SzvHq9z9CVcJp
    qfR0pR15SlvY4Dp/kEzo/bNBw/4hvIY0nFoCfP2PTi1G6W05O9o03sEMkvb0Y24S
    sPiX7Fmr1yqJW+9zBvgfZEuGfp+kS+7ynAkKoasy3PFIP7Au445ueEHL0Xtm7u0N
    jlbavrkQZ5gOQq1P+B3ZFNsEHRrPzCY91lfqLwIDAQABAoIBAQCVFY6Q+K9jXe9K
    TOiAnmSDUT4YNMFiGwJu3Fxj+/PsGmOvRYjWGyATR09LYm76lYoH+5rzvcT8F7vr
    0p4oqdAKcqVwq0/HFaVxAEZURTP8iKqCYzQUd5rSJgUCP8Cx7NhJp6mG/Wukg/Pr
    rCm/SEh9d8xF4dYexaPbEJWSBZBVYGgi9HtwaqUEflifv0knI7icuKGs0RpY88uB
    QQfHhl3bXRAWruVFmEAtCEO4TVhcQhBz9i9AOE8b8C+lTNdiTqfmIzWsFlYkQcl7
    /aB2hBmiKPIsjzFSojIl3yFxrIkIW6PMfvt9uNnuBJ1y+90y5pg4yS+jXQ9h6Zt1
    Lp/odmbBAoGBAO6aTEldj13We72O+w6NF8IdZZjJmk84kbqpI8x/9rOfVNXjC4hz
    /yodxQNGpCQyKlg2HaXclTo5p19T1AlK5obtnN+puULkv/PlHGSKcHYUOGszKedB
    ++9p6Ty/PnV+6GdTJdKy0+gz9mNcdVFzeD4JgROjooY2DMdAa5rsNMJhAoGBAMDR
    YxnbepshqMSDZ943mEpHygmF8h+EfJ9BZUsA6WgMqX6Qresrq3ZLR6dbaYoRk9L0
    IgibYHbAh4Rps4NyXA3XxJWWJ2cil6RR8E6t1E4jBzPYFmkwlF7t4kd6XjoGBpob
    Nj0NmfmMm8GK4xMUTedCe4aLiNaVFcvdg8ZCCxaPAoGBAKyG7XpvKGdV24upg2d2
    JiO6Vegwfl+iK92ox7XrIVuobhNqZMB5/5tYg0hnH/D8RRobpzxzT4QWhCut1bgS
    bLZLwg8IDmmMNjAJDoq0f7Uh0dnR2Q7a62ymTHwcXPFgnnN37/V2UTuptxMJm9sV
    f3B8NtUYkUAyfPLmZehTu6KBAoGBALXfi2Ojc4WKfT9HV5zywbIm/vp2nsh91nL9
    Y0cZCBA+CU45t+LgYS4GmgLRJb63D8FmyAdoT9gTiIAsl8gAAbaI9IPIi0gsB+9V
    3p7INj6xqaSMSa9UxE66gbq8QM7oSifoTQPPpZIOwAgSMlgXyde+DPf++8az/0g5
    nIdQWlcfAoGBAKdmWEQTvvfq6mLZQEPBSV8/VQlSleVdbZzxaNqWIjipF8hXlzQF
    DkK6QtJiN6+JRTnqd0FMmVMWraeN8QHhksuPYNDShaZcOrXovrD0BvYAsTS2pa1B
    x7Gv6fFyIkvkQa0e/S3fxBeTX/MJp9vW3AKJkwOSBhnZZVHD7qIBXLEw
    -----END RSA PRIVATE KEY-----